import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import { useEffect } from 'react';
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(()=> {
    document.querySelector('body').classList.add('d-flex', 'h-100', 'v-100', 'text-center', 'text-bg-dark');
    document.querySelector('html').classList.add('h-100');
  });
  return (
    <>
      <Head>
        <title>42 Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossOrigin="anonymous" />
      </Head>

      <div className="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
        <header className="mb-auto">
          <div>
            <h3 className="float-md-start mb-0">Cover</h3>
            <nav className="nav nav-masthead justify-content-center float-md-end">
              <a className="nav-link fw-bold py-1 px-0 active" aria-current="page" href="#">Home</a>
              <a className="nav-link fw-bold py-1 px-0" href="#">Features</a>
              <a className="nav-link fw-bold py-1 px-0" href="#">Contact</a>
            </nav>
          </div>
        </header>

        <main className="px-3">
          <h1>42 Event</h1>
          <p className="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
          <p className="lead">
            <Link href="/api/auth" className="btn btn-lg btn-light fw-bold border-white bg-white">Sign In</Link>
          </p>
        </main>

        <footer className="mt-auto text-white-50">
          <p>Cover template for <a href="https://getbootstrap.com/" className="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" className="text-white">@mdo</a>.</p>
        </footer>
      </div>
    </>
  )
}
